name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --user django
    - name: Run Django unit tests
      run: |
        cd testprojectairline/airline
        python3 manage.py test