# .yml file path should be gitrepo/.github/workflows/filename.yml
name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |  # airline is the directory that contains the manage.py file
          cd airline  
          pip3 install --user django
          python3 manage.py test
